### ISSUE TITLE
Accounting for globs and arrays

### ISSUE THREAD

**Issue by Antonio-Laguna** [firstandthird/bower-files#4]
Currently, the library doesn't handle globs nor arrays on the main file which apparently are perfectly valid.

Error is: 

```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at getDependencies (index.js:23:27)
    at Logger.<anonymous> (index.js:77:11)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (lib/Logger.js:29:39)
    at lib/commands/list.js:75:16
    at _fulfilled (node_modules/bower/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (node_modules/bower/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (node_modules/bower/node_modules/q/q.js:760:13)
    at node_modules/bower/node_modules/q/q.js:574:44
```

Example input:

```
[ 'css/ionic.css',
  'fonts/*',
  'js/ionic.js',
  'js/ionic-angular.js' ]
```

**Comment by jgallen23** [comment]
huh.  didn't realize that was valid.  maybe we should use the glob lib
